### PR TITLE
Add `jiter = "^0.5.0"` to deps

### PR DESCRIPTION
**Pull request by jimkring**
this package must be installed for tool calling

### CODE REVIEW

**Comment by willbakst** [comment]
This is a good catch, but I think this is only true for v1, can you confirm your version?

I just want to make sure we include this in the right branch.

**Comment by jimkring** [comment]
I had the issue in v1 beta.

**Comment by willbakst** [comment]
Got it. Can you close this PR and reopen a new on that pulls in the v1 branch please?

**Comment by willbakst** [comment]
Adding this to v1 for the upcoming release.

**Comment by jimkring** [comment]
Sounds good @willbakst. Thanks for taking care of v1

**Pull request closed without merging**
