### PR TITLE
feat: Track costs for streaming with OpenAI

### PR DESCRIPTION
**Pull request by tvj15**
Made changes as discussed on  #214. 

Now,  the user when iterating through the stream can check if cost exists like this:
```python
from mirascope.openai import OpenAICall

class BookRecommender(OpenAICall):
    prompt_template = "Please recommend a {genre} book."

    genre: str


stream = BookRecommender(genre="fantasy").stream()
for chunk in stream:
    print(chunk.content, end="")
    if chunk.cost:
        print(chunk.cost)
```

### CODE REVIEW

**Comment by brenkao** [comment]
Changes look good! can you update https://docs.mirascope.io/latest/concepts/tracking_costs_for_llm_providers/#cost-tracking-for-streaming to reflect your new updates?

**Comment by tvj15** [comment]
> Changes look good! can you update https://docs.mirascope.io/latest/concepts/tracking_costs_for_llm_providers/#cost-tracking-for-streaming to reflect your new updates?

Sure!

**Review by willbakst — APPROVED** [review]
Great work! Thank you for contributing 🙏

**Comment by willbakst** [comment]
@tvj15 can you please merge in current dev? I made a change to the GitHub action for codecov that will hopefully resolve there rate limit failures.

**Comment by willbakst** [comment]
This closes #214 

@tvj15 I tried merging dev into your branch, but I'm running into issues. Did you make sure to check the box for allowing maintainers to submit changes? Wondering if that was un-checked or if there's a separate issue happening.

**Comment by tvj15** [comment]
> This closes #214
> 
> @tvj15 I tried merging dev into your branch, but I'm running into issues. Did you make sure to check the box for allowing maintainers to submit changes? Wondering if that was un-checked or if there's a separate issue happening.

I am not sure about this. Shall I raise a new PR into dev?

**Comment by willbakst** [comment]
Hmm, probably an issue on my end then.

For now, can you just merge dev into this PR so I can re-run the workflows?

**Pull request merged**
